version: "3.9"

services:
  ibsrv:
    image: camojiet/1c-single:latest
    container_name: 1c-single
    ports:
      - "8314:8314"
    volumes:
      - ./fs-data:/fs-data
      - ./storage:/storage
    restart: unless-stopped
    environment:
      PORT: 8314